/**
 * Explicitly labelled synthetic data for screenshots and interaction tests.
 * @scope spec://org.vibevm.zap/lens/PROP-002#semantic-map
 */
import {
  QuicklensRefSchema,
  QuicklensSnapshotSchema,
  type Metric,
  type QuicklensDataSource,
  type QuicklensResult,
  type QuicklensSnapshot,
} from "../quicklens-model/index.ts";

const unknown = (reason: string): Metric => ({ state: "unknown", reason });
const known = (value: string, unit: string | null, explanation: string): Metric => ({
  state: "known",
  value,
  unit,
  explanation,
});

const DEMO_SNAPSHOT: QuicklensSnapshot = QuicklensSnapshotSchema.parse({
  sourceMode: "demo",
  sourceLabel: "Demo workspace · synthetic planning data",
  phase: "partial",
  phaseDetail: "Demonstration data omits backend authority and live execution history.",
  capturedAt: "2026-09-15T04:00:00.000Z",
  revision: "12",
  objects: [
    {
      ref: "outcome.quicklens",
      category: "other",
      semanticType: "outcome",
      title: "Visual planning workspace",
      description: "The active synthetic goal for this demonstration.",
      purpose: "Keep a live plan understandable and controllable across agent and human work.",
      expectedResult: "The graph explains goal structure and verified prerequisite order.",
      acceptance: "Both graph views remain truthful under filtering and partial data.",
      status: { code: "active", label: "Active goal", tone: "active" },
      metrics: {
        complexity: unknown("Outcomes do not inherit task complexity."),
        difficulty: unknown("No outcome difficulty measure is supplied."),
        effort: unknown("No outcome effort measure is supplied."),
        waiting: unknown("No outcome waiting measure is supplied."),
        uncertainty: known("low", null, "This synthetic goal identity is explicit."),
      },
      provenance: [{ sourceType: "outcome", label: "Synthetic active outcome", detail: null }],
      position: null,
    },
    {
      ref: "strategy.quicklens",
      category: "other",
      semanticType: "strategy",
      title: "Communication-first strategy",
      purpose: "Build the durable communication foundation before connected client surfaces.",
      acceptance: "All planned work remains tied to the active outcome.",
      status: { code: "adopted", label: "Adopted", tone: "success" },
      metrics: {
        complexity: unknown("Strategies do not inherit task complexity."),
        difficulty: unknown("No strategy difficulty measure is supplied."),
        effort: unknown("No strategy effort measure is supplied."),
        waiting: unknown("No strategy waiting measure is supplied."),
        uncertainty: known("low", null, "The demo marks this strategy explicitly."),
      },
      provenance: [{ sourceType: "strategy", label: "Synthetic adopted strategy", detail: null }],
      position: null,
    },
    {
      ref: "milestone.communication",
      category: "milestone",
      semanticType: "adopted_milestone",
      title: "Communication foundation",
      purpose: "Keep agent questions durable while normal conversation continues.",
      acceptance: "Concurrent child questions survive restart and route to the correct inbox.",
      status: { code: "done", label: "Accepted", tone: "success" },
      metrics: {
        complexity: known("3", "points", "Several delivery states with bounded transitions."),
        difficulty: known("2", "level", "Mechanically verified protocol behavior."),
        effort: known("8", "hours", "Measured implementation effort."),
        waiting: known("0", "items", "No outstanding dependency."),
        uncertainty: known("low", null, "Host consumption remains separately observed."),
      },
      provenance: [{ sourceType: "milestone", label: "PROP-001 acceptance", detail: null }],
      position: { x: -0.72, y: -0.08 },
    },
    {
      ref: "milestone.quicklens",
      category: "milestone",
      semanticType: "adopted_milestone",
      title: "Quicklens workspace",
      purpose: "Make the active plan legible and controllable without hiding uncertainty.",
      acceptance: "Browser and Electron share one renderer with real backend injection.",
      status: { code: "active", label: "In progress", tone: "active" },
      metrics: {
        complexity: known("5", "points", "Graph, questions, plan controls and two shells."),
        difficulty: known("3", "level", "Cross-platform lifecycle and security boundaries."),
        effort: unknown("The live backend integration is still being sized."),
        waiting: known("1", "dependency", "Backend plan workflow adapter."),
        uncertainty: known("medium", null, "Visual acceptance and live workflow remain."),
      },
      provenance: [{ sourceType: "milestone", label: "PROP-002 shared client", detail: null }],
      position: { x: 0.15, y: -0.52 },
    },
    {
      ref: "task.protocol",
      category: "task",
      semanticType: "implementation_task",
      title: "Build durable communication",
      purpose: "Carry concurrent parent and child questions through restart.",
      acceptance: "Delivery, acknowledgement and actor identity remain distinct.",
      status: { code: "done", label: "Complete", tone: "success" },
      metrics: {
        complexity: known("3", "points", "Durable actor and delivery transitions."),
        difficulty: known("2", "level", "Verified through restart and duplicate tests."),
        effort: unknown("Historical effort was not recorded in this fixture."),
        waiting: known("0", "items", "Completed."),
        uncertainty: known("low", null, "The synthetic completion state is explicit."),
      },
      provenance: [{ sourceType: "task", label: "Synthetic completed start", detail: null }],
      position: null,
    },
    {
      ref: "task.renderer",
      category: "task",
      semanticType: "implementation_task",
      title: "Build reusable renderer",
      description: "A shared Qwik workspace for the browser and secured Electron shell.",
      purpose: "Present graph, structured cards and explicit data states.",
      expectedResult: "The same readable plan view and controls operate in both shells.",
      acceptance: "Search, filters, selection and themes work in both shells.",
      reasons: ["The shared renderer keeps visual behavior consistent across platforms."],
      blockers: [],
      blockerSummary: "No renderer blockers are established in this synthetic snapshot.",
      status: { code: "active", label: "Building", tone: "active" },
      metrics: {
        complexity: known("3", "points", "One renderer with bounded panels."),
        difficulty: known("2", "level", "Established Qwik and Sigma lifecycle."),
        effort: unknown("Not yet measured."),
        waiting: known("0", "items", "Can proceed independently."),
        uncertainty: known("low", null, "Implementation surface is explicit."),
      },
      provenance: [{ sourceType: "task", label: "UI implementation packet", detail: null }],
      position: { x: 0.62, y: -0.08 },
    },
    {
      ref: "task.plan-adapter",
      category: "task",
      semanticType: "integration_task",
      title: "Wire plan controls",
      purpose: "Map ZAP reads, previews, admission and reconciliation into the client seam.",
      acceptance: "Stale bases refuse before any operation is applied.",
      status: { code: "active", label: "Building", tone: "active" },
      metrics: {
        complexity: known("5", "points", "Authority and economics remain service-owned."),
        difficulty: known("4", "level", "Requires exact basis and reconciliation semantics."),
        effort: unknown("Waiting for the adapter implementation."),
        waiting: known("0", "items", "The communication prerequisite is complete."),
        uncertainty: known("medium", null, "Service contract is still integrating."),
      },
      provenance: [{ sourceType: "task", label: "Backend workflow lane", detail: null }],
      position: { x: 0.42, y: 0.7 },
    },
    {
      ref: "task.integration",
      category: "task",
      semanticType: "verification_task",
      title: "Verify connected shells",
      purpose: "Exercise browser and Electron against the same live plan service.",
      acceptance: "Both parallel client branches pass before connected acceptance.",
      status: { code: "planned", label: "Planned", tone: "neutral" },
      metrics: {
        complexity: known("2", "points", "One bounded integration boundary."),
        difficulty: known("2", "level", "Depends on two independently testable branches."),
        effort: unknown("No estimate is supplied."),
        waiting: known("2", "prerequisites", "Renderer and authority adapter."),
        uncertainty: known("medium", null, "Live service evidence is still required."),
      },
      provenance: [{ sourceType: "task", label: "Synthetic integration step", detail: null }],
      position: null,
    },
    {
      ref: "resource.broker",
      category: "resource",
      semanticType: "running_service",
      title: "Lens broker",
      purpose: "Durable questions, actor inboxes and delivery acknowledgement.",
      acceptance: null,
      status: { code: "healthy", label: "Healthy", tone: "success" },
      metrics: {
        complexity: unknown("Resources do not inherit task complexity."),
        difficulty: unknown("No difficulty measure supplied."),
        effort: unknown("No effort measure supplied."),
        waiting: known("0", "items", "Available."),
        uncertainty: known("low", null, "Health is directly observed in the fixture."),
      },
      provenance: [{ sourceType: "service", label: "Local broker", detail: "Synthetic health" }],
      position: { x: -0.1, y: 0.92 },
    },
    {
      ref: "fact.host-limit",
      category: "other",
      semanticType: "verified_host_fact",
      title: "Idle wake varies by host",
      purpose: "Keep transport delivery distinct from model consumption.",
      acceptance: null,
      status: { code: "known", label: "Verified constraint", tone: "neutral" },
      metrics: {
        complexity: unknown("Facts are not tasks."),
        difficulty: unknown("Facts are not tasks."),
        effort: unknown("Facts are not tasks."),
        waiting: unknown("No waiting fact supplied."),
        uncertainty: known("low", null, "Constraint is documented per host."),
      },
      provenance: [{ sourceType: "fact", label: "Host adapter evidence", detail: null }],
      position: { x: -0.78, y: 0.65 },
    },
  ],
  relationships: [
    {
      ref: "edge.strategy.protocol.contains",
      source: "strategy.quicklens",
      target: "task.protocol",
      semanticType: "contains",
      label: "contains",
      provenance: [],
    },
    {
      ref: "edge.strategy.renderer.contains",
      source: "strategy.quicklens",
      target: "task.renderer",
      semanticType: "contains",
      label: "contains",
      provenance: [],
    },
    {
      ref: "edge.strategy.adapter.contains",
      source: "strategy.quicklens",
      target: "task.plan-adapter",
      semanticType: "contains",
      label: "contains",
      provenance: [],
    },
    {
      ref: "edge.strategy.integration.contains",
      source: "strategy.quicklens",
      target: "task.integration",
      semanticType: "contains",
      label: "contains",
      provenance: [],
    },
    {
      ref: "edge.protocol.renderer.prerequisite",
      source: "task.protocol",
      target: "task.renderer",
      semanticType: "work_prerequisite",
      label: "prerequisite",
      provenance: [],
    },
    {
      ref: "edge.protocol.adapter.prerequisite",
      source: "task.protocol",
      target: "task.plan-adapter",
      semanticType: "work_prerequisite",
      label: "prerequisite",
      provenance: [],
    },
    {
      ref: "edge.renderer.integration.prerequisite",
      source: "task.renderer",
      target: "task.integration",
      semanticType: "work_prerequisite",
      label: "prerequisite",
      provenance: [],
    },
    {
      ref: "edge.adapter.integration.prerequisite",
      source: "task.plan-adapter",
      target: "task.integration",
      semanticType: "work_prerequisite",
      label: "prerequisite",
      provenance: [],
    },
    {
      ref: "edge.protocol.communication.contributes",
      source: "task.protocol",
      target: "milestone.communication",
      semanticType: "contributes_to",
      label: "contributes to",
      provenance: [],
    },
    {
      ref: "edge.renderer.quicklens.contributes",
      source: "task.renderer",
      target: "milestone.quicklens",
      semanticType: "contributes_to",
      label: "contributes to",
      provenance: [],
    },
    {
      ref: "edge.adapter.quicklens.contributes",
      source: "task.plan-adapter",
      target: "milestone.quicklens",
      semanticType: "contributes_to",
      label: "contributes to",
      provenance: [],
    },
    {
      ref: "edge.broker.protocol.supports",
      source: "resource.broker",
      target: "task.protocol",
      semanticType: "supports",
      label: "supports",
      provenance: [],
    },
    {
      ref: "edge.host.renderer.affects",
      source: "fact.host-limit",
      target: "task.renderer",
      semanticType: "affects",
      label: "affects",
      provenance: [],
    },
  ],
  navigation: {
    activeOutcomeRef: "outcome.quicklens",
    currentStrategyRef: "strategy.quicklens",
    adoptedPlanRef: "milestone-plan.quicklens.1",
    members: [
      {
        ref: "milestone.communication",
        revisionRef: "milestone_revision:milestone.communication.1",
        isCurrent: true,
      },
      {
        ref: "milestone.quicklens",
        revisionRef: "milestone_revision:milestone.quicklens.1",
        isCurrent: true,
      },
    ],
    focusRef: "milestone.quicklens",
    currentWorkRefs: ["task.renderer", "task.plan-adapter"],
    dependencyDirection: "prerequisite_to_dependent",
    completeness: "complete",
    reassessmentReason: null,
  },
  questions: [
    {
      ref: "question.layout",
      addressedActorLabel: "Renderer worker",
      prompt: "Which card density should the first visual acceptance use?",
      state: "pending",
      revision: "1",
      answerMode: "single_choice",
      choices: [
        { id: "comfortable", label: "Comfortable" },
        { id: "compact", label: "Compact" },
      ],
      answer: null,
      amendmentCount: "0",
    },
    {
      ref: "question.protocol",
      addressedActorLabel: "Protocol worker",
      prompt: "Should late answers forward to the parent?",
      state: "answered",
      revision: "2",
      answerMode: "free_text",
      choices: [],
      answer: "Yes, preserve the original recipient and question identity.",
      amendmentCount: "0",
    },
  ],
  questionAnswer: { enabled: false, reason: "Demo mode does not answer live questions." },
  agentTargets: [
    {
      ref: "actor.demo-coordinator",
      label: "Demo coordinator",
      host: "synthetic",
      parentRef: null,
      state: "active",
      eligible: true,
      reason: null,
    },
  ],
  plan: {
    outcomeLabel: "Ship a trustworthy visual planning workspace",
    strategyLabel: "Communication first, client second",
    planLabel: "Quicklens MVP",
    basis: {
      storeRef: "demo.store",
      baseRef: "demo.base",
      revision: "12",
      sourceBasisRef: "demo.source-basis",
    },
    state: "held",
    detail: "Demo mode cannot prepare or admit real plan operations.",
    actions: {
      propose: { enabled: false, reason: "Demo mode has no planning authority." },
      preview: { enabled: false, reason: "Demo mode has no planning authority." },
      apply: { enabled: false, reason: "Demo mode never applies operations." },
      reconcile: { enabled: false, reason: "Demo mode has no uncertain operation." },
      decide: { enabled: false, reason: "Demo mode has no held owner decision." },
    },
  },
});

export function createQuicklensDemoDataSource(): QuicklensDataSource {
  const unsupported = <T>(): Promise<QuicklensResult<T>> =>
    Promise.resolve({
      ok: false,
      error: {
        code: "unsupported",
        message: "Demo mode does not perform live communication or planning operations.",
        recovery: "Launch Quicklens with an injected live data source.",
      },
    });
  return {
    read: ({ signal }) =>
      Promise.resolve(
        signal.aborted
          ? {
              ok: false,
              error: {
                code: "cancelled",
                message: "Demo snapshot load was cancelled.",
                recovery: "Refresh the demo when ready.",
              },
            }
          : { ok: true, value: DEMO_SNAPSHOT },
      ),
    answerQuestion: unsupported,
    proposePlanIntent: unsupported,
    previewPlan: unsupported,
    applyPlan: unsupported,
    reconcilePlan: unsupported,
    decidePlan: unsupported,
  };
}

export const QUICKLENS_DEMO_LABEL_REF = QuicklensRefSchema.parse("demo.label");
