[package]
name = "zap-store"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
redb.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
specmark.workspace = true
tempfile.workspace = true
zap-core.workspace = true
zap-wire.workspace = true

[lints]
workspace = true
