[package]
name = "zap-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license-file.workspace = true
publish.workspace = true

[dependencies]
base64.workspace = true
bytes.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
serde.workspace = true
serde_json.workspace = true
specmark.workspace = true
tokio.workspace = true
zap-api.workspace = true
zap-core.workspace = true
zap-domain.workspace = true
zap-legacy.workspace = true
zap-runtime.workspace = true
zap-store.workspace = true
zap-wire.workspace = true

[lints]
workspace = true

[dev-dependencies]
redb.workspace = true
serde-value.workspace = true
tempfile.workspace = true
