fn assessment(
    name: &str,
    baseline_id: ChangeBaselineId,
    alternative_id: ChangeAlternativeId,
    effect: ChangeEffect,
    comparison_basis_request: BasisRequest,
    comparison_basis_digest: RelevantBasisDigest,
    scope: &DerivedAffectedScope,
) -> Result<ChangeAssessmentRecord, ZapError> {
    let zero = HoursInterval::new(HoursMicros::ZERO, Some(HoursMicros::ZERO))?;
    let cost = HoursMicros::new(1_000_000);
    let categories = CostCategoryKind::ALL
        .into_iter()
        .map(|category| {
            Ok(CostCategory {
                category,
                applicability: Applicability::Included,
                agent_hours: zero,
                elapsed: zero,
                consequence: ConsequenceBand::Negligible,
                basis: BoundedText::parse("No extra category cost")?,
                evidence_refs: Vec::new(),
            })
        })
        .collect::<Result<Vec<_>, ZapError>>()?;
    let policy = ChangePolicyRecord::default_policy()?;
    Ok(ChangeAssessmentRecord {
        assessment_id: ChangeAssessmentId::parse(&format!("assessment.{name}"))?,
        change_id: ChangeId::parse(&format!("change.{name}"))?,
        baseline_id,
        summary: BoundedText::parse("Rebind unchanged executable graph")?,
        necessity: ChangeNecessity {
            class: NecessityClass::OptionalImprovement,
            obligation_ids: Vec::new(),
            constraint_refs: Vec::new(),
            problem: BoundedText::parse("Advance the current semantic lowering")?,
            basis: BoundedText::parse("Current strategy remains applicable")?,
            evidence_refs: Vec::new(),
        },
        affected_work_ids: scope.affected_work_ids.clone(),
        dependent_work_ids: scope.dependent_work_ids.clone(),
        affected_subjects: scope.subjects.clone(),
        scope_roots: effect.subjects.clone(),
        scope_direct_work_ids: effect
            .subjects
            .iter()
            .filter_map(|subject| match subject {
                SubjectRef::Work(id) => Some(id.clone()),
                _ => None,
            })
            .collect(),
        affected_scope_digest: None,
        unknown_impact: scope.unknown_boundary.clone(),
        comparison_basis_request: comparison_basis_request.clone(),
        comparison_basis_digest,
        policy_id: policy.policy_id.clone(),
        policy_revision: policy.revision,
        policy_digest: policy.digest()?,
        team_model: TeamCapacityModel {
            model_id: BoundedText::parse("team.lowering")?,
            profile_digest: PayloadDigest::hash(b"team-lowering"),
            executor_classes: vec![ExecutorCapacity {
                class_id: BoundedText::parse("middle")?,
                capability_ids: vec![BoundedText::parse("rust")?],
                nominal_capacity: 1,
            }],
            nominal_parallelism: 1,
            resource_capacities: Vec::new(),
            scheduling_assumptions: vec![BoundedText::parse("One executor")?],
            evidence_refs: Vec::new(),
        },
        alternatives: vec![
            ChangeAlternative {
                alternative_id: alternative_id.clone(),
                kind: AlternativeKind::Proposal,
                summary: BoundedText::parse("Apply the prepared lowering")?,
                solves_mandatory_problem: true,
                preserved_obligations: Vec::new(),
                sacrificed_obligations: Vec::new(),
                utility: UtilityAssessment {
                    overall: UtilityBand::High,
                    owner_benefit: UtilityBand::High,
                    risk_reduction: UtilityBand::Moderate,
                    urgency: UtilityBand::Moderate,
                    strategic_optionality: UtilityBand::Moderate,
                    reversibility: UtilityBand::High,
                    confidence: ConfidenceBand::High,
                    basis: BoundedText::parse("Prepared effect is exact")?,
                    evidence_refs: Vec::new(),
                },
                cost: IncrementalCost {
                    expected_elapsed: Some(cost),
                    elapsed_interval: HoursInterval::new(cost, Some(cost))?,
                    expected_passive_wait: Some(HoursMicros::ZERO),
                    passive_wait_interval: zero,
                    total_agent_hours: Some(cost),
                    agent_hours_interval: HoursInterval::new(cost, Some(cost))?,
                    precision: CostPrecision::BoundedEstimate,
                    consequence: ConsequenceBand::Negligible,
                    categories: categories.clone(),
                    unknowns: Vec::new(),
                    excluded_costs: Vec::new(),
                    attribution_summary: BoundedText::parse("One prepared effect")?,
                },
                feasibility: zap_domain::economics::Feasibility::Feasible,
                effects: vec![effect],
                no_op_basis_request: None,
                basis: BoundedText::parse("Prepared against current state")?,
                evidence_refs: Vec::new(),
            },
            ChangeAlternative {
                alternative_id: ChangeAlternativeId::parse("alternative.no-op")?,
                kind: AlternativeKind::NoOp,
                summary: BoundedText::parse("Keep the current lowering")?,
                solves_mandatory_problem: false,
                preserved_obligations: Vec::new(),
                sacrificed_obligations: Vec::new(),
                utility: UtilityAssessment {
                    overall: UtilityBand::Low,
                    owner_benefit: UtilityBand::Low,
                    risk_reduction: UtilityBand::Low,
                    urgency: UtilityBand::Low,
                    strategic_optionality: UtilityBand::Low,
                    reversibility: UtilityBand::High,
                    confidence: ConfidenceBand::High,
                    basis: BoundedText::parse("No semantic improvement")?,
                    evidence_refs: Vec::new(),
                },
                cost: IncrementalCost {
                    expected_elapsed: Some(HoursMicros::ZERO),
                    elapsed_interval: zero,
                    expected_passive_wait: Some(HoursMicros::ZERO),
                    passive_wait_interval: zero,
                    total_agent_hours: Some(HoursMicros::ZERO),
                    agent_hours_interval: zero,
                    precision: CostPrecision::BoundedEstimate,
                    consequence: ConsequenceBand::Negligible,
                    categories,
                    unknowns: Vec::new(),
                    excluded_costs: Vec::new(),
                    attribution_summary: BoundedText::parse("No-op")?,
                },
                feasibility: zap_domain::economics::Feasibility::Feasible,
                effects: Vec::new(),
                no_op_basis_request: Some(comparison_basis_request),
                basis: BoundedText::parse("Current lowering remains")?,
                evidence_refs: Vec::new(),
            },
        ],
        recommended_alternative_id: Some(alternative_id),
        recommendation: Recommendation::TakeProposal,
        admission: AdmissionDisposition::Automatic,
        comparison_reasons: vec![BoundedText::parse("Bounded useful change")?],
        estimation: EstimationUsage {
            elapsed: HoursMicros::new(100_000),
            agent_hours: HoursMicros::new(100_000),
            stopped_because: EstimationStop::Sufficient,
            assumptions: vec![BoundedText::parse("Stable inputs")?],
            evidence_refs: Vec::new(),
        },
        hold_id: None,
        adjudicated: false,
        resolved: false,
        revision: Revision::new(1),
    })
}
